// Code generated by "stringer -type=Other"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[alpha-0]
	_ = x[beta-1]
	_ = x[gamma-2]
	_ = x[delta-3]
}

const _Other_name = "alphabetagammadelta"

var _Other_index = [...]uint8{0, 5, 9, 14, 19}

func (i Other) String() string {
	if i < 0 || i >= Other(len(_Other_index)-1) {
		return "Other(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Other_name[_Other_index[i]:_Other_index[i+1]]
}
